name: Sign webextension
on:
  push: 
    branches: master
    paths: [ "ophirofox/**" ]

defaults:
  run:
    working-directory: ./ophirofox

jobs:
  publish-to-amo:
    name: Build and publish the extension
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install --global web-ext
      - id: version
        run: echo ::set-output name=version::$(jq -r ".version + \".$(($(date +%s)/100000)).$(($(date +%s)%65535))\"" < manifest.json)
      - run: jq ".version |= \"$VERSION\"" < manifest.json > manifest.json.tmp && mv manifest.json.tmp manifest.json
        env:
          VERSION: ${{ steps.version.outputs.version }}
      - run: web-ext lint
      - run: web-ext build
      - run: web-ext sign --channel=unlisted
        env:
          WEB_EXT_API_KEY: ${{ secrets.AMO_JWT_ISSUER }}
          WEB_EXT_API_SECRET: ${{ secrets.AMO_JWT_SECRET }}
      - run: ls -lah ./web-ext-artifacts
      - id: filename
        run: echo ::set-output name=filename::$(echo $PWD/web-ext-artifacts/*xpi)
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.version }}
          release_name: Release ${{ steps.version.outputs.version }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.filename.outputs.filename }}
          asset_name: ophirofox.xpi
          asset_content_type: application/zip
