name: Sign webextension
on:
  push: 
    branches: master

jobs:
  publish-to-amo:
    name: Build and publish the extension
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install --global web-ext
      - run: jq ".version |= . + \"-$(date)\"" < manifest.json > manifest.json.tmp && mv manifest.json.tmp manifest.json
      - run: web-ext lint
      - run: web-ext build
      - run: web-ext sign -channel=unlisted
        env:
          WEB_EXT_API_KEY: ${{ secrets.AMO_JWT_ISSUER }}
          WEB_EXT_API_SECRET: ${{ secrets.AMO_JWT_SECRET }}
      - run: ls -lah
